<?php

namespace Sauron\Symfony;

use Symfony\Component\Filesystem\Path;

/**
 * Stands in for symfony-lsp so the Docker configuration is written just before
 * the server starts, from the worktree Zed launched it in.
 */
final class Wrapper
{
    public const CONFIG_FILE = '.symfony-lsp.json';

    public static function launcherPath(): string
    {
        return $_SERVER['HOME'] . '/.local/share/sauron-lsp/bin/symfony-lsp';
    }

    /** A POSIX shell launcher, because Zed needs a plain executable to spawn. */
    public static function launcher(string $castorFile): string
    {
        $repository = \dirname($castorFile);
        return <<<SH
            #!/bin/sh
            # Generated by sauron-lsp, do not edit. Run `castor lsp:symfony:wrapper` to refresh.
            #
            # Zed starts a language server in the worktree it serves, so \$PWD is the
            # project. Nothing may be written to stdout here: it is the LSP stream.
            #
            # Castor is run from its own directory on purpose: a project that builds
            # its stack with castor regenerates compose files whenever castor runs
            # inside it, and would rewrite them from the wrong definitions.
            project="\$PWD"
            cd {$repository} || exit 1
            exec castor --castor-file={$castorFile} lsp:symfony:wrap --project="\$project" "\$@"
            SH;
    }

    /**
     * The server binary the Zed extension downloaded, newest first, or whatever
     * is on PATH.
     */
    public static function serverBinary(): ?string
    {
        $candidates = glob($_SERVER['HOME'] . '/.local/share/zed/extensions/work/symfony-language-tools/*/*/symfony-lsp') ?: [];
        rsort($candidates);

        foreach ($candidates as $candidate) {
            if (is_executable($candidate)) {
                return $candidate;
            }
        }

        $onPath = trim((string) shell_exec('command -v symfony-lsp 2>/dev/null'));

        return '' === $onPath ? null : $onPath;
    }

    /**
     * Writes the configuration for a project, and keeps it out of git: the file
     * is ours, not the team's.
     *
     * @return array{written: bool, reason: string}
     */
    public static function configure(string $project): array
    {
        $config = ProjectConfig::build($project);

        if (!isset($config['projects'])) {
            return ['written' => false, 'reason' => 'no containerised application here'];
        }

        $path = Path::join($project, self::CONFIG_FILE);

        if (Workspace::isTracked($project, self::CONFIG_FILE)) {
            return ['written' => false, 'reason' => 'the file is tracked by git, leaving it alone'];
        }

        $json = json_encode($config, \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES | \JSON_THROW_ON_ERROR) . "\n";

        if (is_file($path) && file_get_contents($path) === $json) {
            return ['written' => false, 'reason' => 'already up to date'];
        }

        file_put_contents($path, $json);
        self::exclude($project);

        return ['written' => true, 'reason' => 'written'];
    }

    /** Adds the file to this checkout's local excludes, shared by its worktrees. */
    public static function exclude(string $project): void
    {
        if (Workspace::isIgnored($project, self::CONFIG_FILE)) {
            return;
        }

        $excludeFile = Workspace::excludeFile($project);

        if (null === $excludeFile || !is_dir(\dirname($excludeFile))) {
            return;
        }

        $current = is_file($excludeFile) ? file_get_contents($excludeFile) : '';

        if (str_contains($current, self::CONFIG_FILE)) {
            return;
        }

        file_put_contents(
            $excludeFile,
            rtrim($current, "\n") . "\n" . self::CONFIG_FILE . "\n",
        );
    }
}
